services:
  - type: web
    name: resume-builder 
    env: node 
    plan: free 
    region: oregon 
    rootDir: .
    # Add buildpacks. The order might matter.
    # The heroku-community/puppeteer buildpack is a common choice.
    # Render might have its own preferred buildpacks or way to specify system dependencies.
    # You might need to add the standard Node.js buildpack if it's not automatically included.
    buildpacks:
      - https://github.com/jontewks/puppeteer-heroku-buildpack 
      # - heroku/nodejs # Add this if Render requires specifying the Node.js buildpack too
    buildCommand: "npm install" 
    startCommand: "npm start" 
    healthCheckPath: / 
    envVars:
      - key: NODE_ENV
        value: production 
      - key: MONGODB_URI
        # This MUST be set in Render's dashboard environment variables
      # Tell puppeteer-core NOT to download any browser.
      # The buildpack is responsible for providing Chromium.
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      # PUPPETEER_EXECUTABLE_PATH is usually not needed when a buildpack provides Chrome,
      # as it's often installed in a standard system path.
      # If issues persist, you might need to find the path the buildpack installs Chrome to
      # and set PUPPETEER_EXECUTABLE_PATH to that (e.g., /usr/bin/google-chrome-stable).
    buildFilter:
      paths:
        - "models/**"
        - "public/**"
        - "routes/**"
        - "views/**"
        - "package.json"
        - "package-lock.json" 
        - "server.js"
        - "render.yaml" 
      ignoredPaths:
        - "*.md"
        - ".gitignore"
        - "docs/**"