services:
  - type: web
    name: resume-builder 
    env: node 
    plan: free 
    region: oregon 
    rootDir: .
    buildCommand: "npm install" 
    startCommand: "npm start" 
    healthCheckPath: / 
    envVars:
      - key: NODE_ENV
        value: production 
      - key: MONGODB_URI
        # This should be set in Render's dashboard environment variables
        # Example: mongodb+srv://user:pass@cluster.mongodb.net/dbname
      - key: PUPPETEER_CACHE_DIR # Puppeteer will download Chromium here
        value: /opt/render/.cache/puppeteer
      # Force Puppeteer to use the specific path from the error log.
      # This is less robust if you update Puppeteer, as the versioned path will change.
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.55/chrome-linux64/chrome
      # Ensure PUPPETEER_SKIP_CHROMIUM_DOWNLOAD is NOT set to true, or is absent,
      # so Puppeteer attempts to download its browser into the cache dir.
    buildFilter:
      paths:
        - "models/**"
        - "public/**"
        - "routes/**"
        - "views/**"
        - "package.json"
        - "package-lock.json" 
        - "server.js"
        - "render.yaml" 
      ignoredPaths:
        - "*.md"
        - ".gitignore"
        - "docs/**"