services:
  - type: web
    name: resume-builder 
    env: node 
    plan: free 
    region: oregon 
    rootDir: .
    buildCommand: "npm install" 
    startCommand: "npm start" 
    healthCheckPath: / 
    envVars:
      - key: NODE_ENV
        value: production 
      - key: MONGODB_URI
        # Set the actual MONGODB_URI value in the Render dashboard's Environment section
        value: YOUR_MONGODB_ATLAS_CONNECTION_STRING_GOES_HERE 
      # PUPPETEER_SKIP_CHROMIUM_DOWNLOAD should NOT be set to true.
      # We want Puppeteer to download its browser.
      - key: PUPPETEER_CACHE_DIR # Explicitly set the cache directory for Puppeteer
        value: /opt/render/.cache/puppeteer
      # ONLY TRY THIS IF ATTEMPT 1 FAILS
      # - key: PUPPETEER_EXECUTABLE_PATH
      #   value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.55/chrome-linux64/chrome # Path from your error
    buildFilter:
      # This is a common structure for Puppeteer's self-managed downloads on Linux.
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome-linux/chrome
    buildFilter:s/**"
      paths:iews/**"
        - "models/**"on"
        - "public/**"ck.json" 
        - "routes/**"
        - "views/**"ml" 
        - "package.json"
        - "package-lock.json" 
        - "server.js""
        - "render.yaml" 
      ignoredPaths:        - "*.md"        - ".gitignore"        - "docs/**"